### ISSUE TITLE
only url option returned error

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#6]
Running 

`v.in.sos.py url=http://istsos.geodati.fmach.it/istsos/edenext?`

I got 

```
Traceback (most recent call last):
  File "v.in.sos.py", line 266, in <module>
    main()
  File "v.in.sos.py", line 143, in main
    handle_not_given_options(service)
  File "v.in.sos.py", line 197, in handle_not_given_options
    for observed_property in service[options['offering']].observed_properties:
  File "/usr/lib/python2.7/dist-packages/owslib/swe/observation/sos100.py", line 41, in __getitem__
    raise KeyError("No Observational Offering with id: %s" % id)
KeyError: 'No Observational Offering with id: '
```

It should return that flags or other otpions should be added

**Comment by lucadelu** [comment]
Please rewrite the error sentence with "You have to define any flags or use 'output' and 'offering' parameters to get the data"

After this you can close this ticket

**Comment by lucadelu** [comment]
Now, with the same request, I got new error

```
WARNING: Illegal filename <>. Cannot start with '.' or be 'NULL'.
Traceback (most recent call last):
  File "v.in.sos.py", line 336, in <module>
    main()
  File "v.in.sos.py", line 149, in main
    new = VectorTopo(options['output'])
  File "/home/lucadelu/compilati/grass72/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/vector/__init__.py", line 276, in __init__
    super(VectorTopo, self).__init__(name, mapset, *args, **kwargs)
  File "/home/lucadelu/compilati/grass72/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/vector/__init__.py", line 61, in __init__
    super(Vector, self).__init__(name, mapset, *args, **kwargs)
  File "/home/lucadelu/compilati/grass72/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/vector/abstract.py", line 73, in __init__
    self.name = name
  File "/home/lucadelu/compilati/grass72/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/vector/abstract.py", line 98, in _set_name
    raise ValueError(str_err.format(newname))
ValueError: Map name  not valid
```
